image: ruby:2.4.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install --no-ri --no-doc awesome_print minitest
          - ./test.sh
